export function generatePackageJson(config) {
  const isTS = config.language === 'TypeScript';
  const isESM = config.moduleSystem === 'ES Modules';

  const dependencies = {
    "express": "^5.0.1",
    "dotenv": "^16.4.7",
    "cors": "^2.8.5",
    "helmet": "^8.0.0",
    "compression": "^1.8.0",
    "cookie-parser": "^1.4.7",
    "mongoose": "^8.10.0",
    "bcryptjs": "^3.0.2",
    "jsonwebtoken": "^9.0.2",
    "zod": "^3.24.2",
    "express-validator": "^7.2.1",
    "nodemailer": "^9.0.3",
    "googleapis": "^173.0.0"
  };

  const devDependencies = {
    "eslint": "^10.8.0",
    "prettier": "^3.4.2"
  };

  const loggerType = String(config.logger || '').toLowerCase();
  if (loggerType.includes('pino')) {
    dependencies["pino"] = "^9.6.0";
    dependencies["pino-http"] = "^10.4.0";
    devDependencies["pino-pretty"] = "^13.0.0";
  } else if (loggerType.includes('winston')) {
    dependencies["winston"] = "^3.17.0";
    if (isTS) devDependencies["@types/winston"] = "^2.4.4";
  } else if (loggerType.includes('morgan')) {
    dependencies["morgan"] = "^1.10.0";
    if (isTS) devDependencies["@types/morgan"] = "^1.9.9";
  }

  if (config.swagger) {
    dependencies["swagger-ui-express"] = "^5.0.1";
    if (isTS) devDependencies["@types/swagger-ui-express"] = "^4.1.8";
  }

  if (isTS) {
    devDependencies["typescript"] = "^5.8.3";
    devDependencies["tsx"] = "^4.23.1";
    devDependencies["@types/node"] = "^22.15.0";
    devDependencies["@types/express"] = "^5.0.0";
    devDependencies["@types/cors"] = "^2.8.17";
    devDependencies["@types/cookie-parser"] = "^1.4.8";
    devDependencies["@types/compression"] = "^1.7.5";
    devDependencies["@types/jsonwebtoken"] = "^9.0.8";
    devDependencies["@types/bcryptjs"] = "^2.4.6";
    devDependencies["@types/nodemailer"] = "^6.4.17";
  } else {
    devDependencies["nodemon"] = "^3.1.14";
  }

  if (config.testing) {
    devDependencies["jest"] = "^30.0.0";
    devDependencies["supertest"] = "^7.2.2";
    if (isTS) {
      devDependencies["ts-jest"] = "^29.4.12";
      devDependencies["@types/jest"] = "^30.0.0";
      devDependencies["@types/supertest"] = "^6.0.2";
    }
  }

  const scripts = {};
  if (isTS) {
    scripts["build"] = "tsc";
    scripts["start"] = "node dist/server.js";
    scripts["dev"] = "tsx watch server.ts";
  } else {
    scripts["start"] = "node server.js";
    scripts["dev"] = "nodemon server.js";
  }

  if (config.testing) {
    scripts["test"] = "jest";
  }

  const pkg = {
    name: config.projectName,
    version: "1.0.0",
    description: "Production ready Express backend generated by create-backend-app",
    main: isTS ? "dist/server.js" : "server.js",
    type: isESM ? "module" : "commonjs",
    scripts,
    dependencies,
    devDependencies,
    overrides: {
      "brace-expansion": "5.0.8",
      "glob": "^13.0.6",
      "test-exclude": "^7.0.1",
      "node-domexception": "npm:es-errors@^1.3.0"
    }
  };

  return JSON.stringify(pkg, null, 2);
}
